version: '3'
services:
  accounts-db:
    platform: linux/amd64
    build: ./accounts-db
    ports:
    - "5432:5432"

  userservice:
    platform: linux/amd64
    build: ./api
    ports:
    - "5000:5000"
    links:
    - accounts-db:accounts-db
    environment:
      VERSION: v0.5.0
      PORT: 5000
      ENABLE_TRACING: "true"
      TOKEN_EXPIRY_SECONDS: 3600
      PRIV_KEY_PATH: "/root/.ssh/privatekey"
      PUB_KEY_PATH: "/root/.ssh/publickey"
      SECRET: "test123"
      DB_URI: "postgresql://accountsadmin:accountspwd@accounts-db:5432/accountsdb"
    # Valid levels are debug, info, warning, error, critical. If no valid level is set, gunicorn will default to info.
      LOG_LEVEL: debug


