
FROM ubuntu:latest

# Avoid warnings by switching to noninteractive
ARG DEBIAN_FRONTEND=noninteractive
# update/upgrade APIT
RUN apt update && apt upgrade -y
# install dependencies
RUN apt install -y software-properties-common \
    build-essential \
    curl \
    libpq5 \
    libpq-dev
# add repository for python 3.11
RUN add-apt-repository ppa:deadsnakes/ppa
# update APT library
RUN apt update
# install python 3.11
RUN apt install -y python3.11 \
    python3.11-distutils \
    python3.11-venv\
    python3.11-dev \
    gunicorn3
# install pip
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

RUN python3.11 -m venv venv
# Enable venv
ENV PATH="./venv/bin:$PATH"

# Install dependencies.
ADD requirements.txt /app/requirements.txt
RUN pip install -U pip wheel -r /app/requirements.txt

# Add application code.
COPY . /api/

# Copy logging configuration for gunicorn
COPY logging.conf /logging.conf

#RUN cd /root/.ssh/

#RUN ssh-keygen -t rsa -P $SECRET -b 4096 -m PEM -f privatekey
#RUN mv privatekey.pub publickey

COPY jwtRS256.key /root/.ssh/privatekey
COPY jwtRS256.key.pub /root/.ssh/publickey

# Start server using uvicorn
CMD uvicorn api.main:app --reload